SELECT live.COLUMN_NAME as 'live', audit.COLUMN_NAME as 'audit'
FROM 
(
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CONTACT' 
AND TABLE_SCHEMA='CONTACT'
) live 
left join 
(
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CONTACTCONTACT' 
AND TABLE_SCHEMA='AUDIT') audit ON live.COLUMN_NAME=audit.COLUMN_NAME
where audit.COLUMN_NAME IS NULL