DECLARE @DBName SYSNAME 
--SET @DBName = RTP_BPEPS_PRD01
DECLARE @MasterPageSizeRows int = (SELECT SUM(SIZE) FROM SYS.MASTER_FILES WHERE DATABASE_ID = db_id('RTP_BPEPS_PRD01') and type_desc = 'ROWS')
DECLARE @MasterPageSizeLogs int = (SELECT SUM(SIZE) FROM SYS.MASTER_FILES WHERE DATABASE_ID = db_id('RTP_BPEPS_PRD01') and type_desc = 'LOG')
DECLARE @DiskLocation VARCHAR(256)= 'Y:\MSSQL\RCSTVSQL2K83-01\10.50\01_ISQL2K801\BACKUPS\FULL_RESTORE_TEMP\'
DECLARE @Now SMALLDATETIME = CURRENT_TIMESTAMP
SET @DiskLocation = @DiskLocation + 'RTP_BPEPS_PRD01_FULL_' + REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(32),@Now,120), '-',''), ' ','T'),':','') + '.BAK'



BACKUP DATABASE RTP_BPEPS_PRD01
TO DISK = @DiskLocation
WITH
COMPRESSION, INIT, CHECKSUM, STATS = 5, COPY_ONLY
